version: '3.8'

services:
  redis:
    image: redis:7
    container_name: todo_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:15
    container_name: todo_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ai_todo_user
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: ai_todo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres-data:
